# wrangler.toml
name = "vadli-docs"
compatibility_date = "2025-12-21"
account_id = "747065b1adc6a0ad30cfc001dde4d491"

# 静态资源配置 (Vue + Vite 构建输出目录)
[assets]
directory = "./dist"

# 自定义域名配置
routes = [
  { pattern = "vadli-docs.onecat.dev", zone_name = "onecat.dev" }
]

# 本地开发端口
[dev]
port = 5173
local_protocol = "http"